let all=[], pool=[], current=null, mode='practice', exam=[], examIndex=0, score=0;
const state=JSON.parse(localStorage.getItem('tjcQuizState')||'{"done":0,"right":0,"wrong":[]}');
const panel=document.getElementById('panel'), chapter=document.getElementById('chapter'), search=document.getElementById('search');
function save(){localStorage.setItem('tjcQuizState',JSON.stringify(state))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function filtered(){let c=chapter.value, s=search.value.trim();return all.filter(q=>(!c||q.chapter===c)&&(!s||(q.question+q.chapter+q.category+q.explanation).includes(s)))}
function renderStart(){panel.innerHTML=`<h2>請按「開始出題」</h2><p>目前題庫共 <b>${all.length}</b> 題。可以先選章節，也可以直接開始。</p><div class="small">練習模式會立即顯示答案解析；模擬考會抽 50 題。</div>`}
function pick(){pool=shuffle(filtered()); if(!pool.length){panel.innerHTML='<h2>找不到題目</h2><p>請換章節或關鍵字。</p>';return} current=pool[0]; renderQ(current)}
function renderQ(q){panel.innerHTML=`<div class="meta"><span class="tag">${q.type==='tf'?'是非題':'選擇題'}</span><span class="tag">${q.chapter}</span><span class="tag">${q.category}</span></div><div class="q">${q.question}</div><div id="opts">${q.options.map((o,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div class="row"><button id="next" class="primary">下一題</button></div>`;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i),q));document.getElementById('next').onclick=()=>{ if(mode==='exam') nextExam(); else pick(); }}
function answer(i,q){let ok=i===q.answer; state.done++; if(ok) state.right++; else {let key=q.id;if(!state.wrong.includes(key)) state.wrong.push(key)} save(); document.querySelectorAll('.option').forEach((b,idx)=>{b.disabled=true;if(idx===q.answer)b.classList.add('correct'); if(idx===i&&!ok)b.classList.add('wrong')}); if(mode==='exam'&&ok)score++; let div=document.createElement('div'); div.className='explain'; div.innerHTML=`<b>${ok?'答對了':'答錯了'}</b><br>正確答案：${q.options[q.answer]}<br>${q.explanation}<br><span class="small">來源：${q.source}</span>`; panel.appendChild(div)}
function startExam(){exam=shuffle(filtered()).slice(0,50); examIndex=0; score=0; if(!exam.length){panel.innerHTML='<h2>沒有可考題目</h2>';return} nextExam()}
function nextExam(){ if(examIndex>=exam.length){panel.innerHTML=`<h2>模擬考完成</h2><p class="q">得分：${score} / ${exam.length}</p><button class="primary" onclick="startExam()">再考一次</button>`;return} current=exam[examIndex++]; renderQ(current); panel.insertAdjacentHTML('afterbegin',`<div class="small">第 ${examIndex} / ${exam.length} 題</div>`)}
function wrongBook(){let ids=new Set(state.wrong);let qs=all.filter(q=>ids.has(q.id)); if(!qs.length){panel.innerHTML='<h2>目前沒有錯題</h2><p>答錯的題目會自動放到這裡。</p>';return} pool=shuffle(qs); current=pool[0]; renderQ(current)}
function stats(){let rate=state.done?Math.round(state.right/state.done*100):0;panel.innerHTML=`<h2>學習統計</h2><div class="statgrid"><div class="stat"><b>${all.length}</b>總題數</div><div class="stat"><b>${state.done}</b>已作答</div><div class="stat"><b>${state.right}</b>答對</div><div class="stat"><b>${rate}%</b>正確率</div><div class="stat"><b>${state.wrong.length}</b>錯題</div></div><div class="row"><button onclick="localStorage.removeItem('tjcQuizState');location.reload()">清除紀錄</button></div>`}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;if(mode==='practice')renderStart();if(mode==='exam')panel.innerHTML='<h2>模擬考</h2><p>按開始出題，系統會抽 50 題。</p>';if(mode==='wrong')wrongBook();if(mode==='stats')stats()});
document.getElementById('start').onclick=()=>{if(mode==='exam')startExam();else if(mode==='wrong')wrongBook();else if(mode==='stats')stats();else pick()};
fetch('questions.json').then(r=>r.json()).then(qs=>{all=qs;[...new Set(all.map(q=>q.chapter))].forEach(c=>chapter.insertAdjacentHTML('beforeend',`<option>${c}</option>`));renderStart()}).catch(()=>panel.innerHTML='<h2>題庫載入失敗</h2><p>請確認 questions.json 有上傳。</p>');
